# Generated by Django 5.0.4 on 2024-05-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
